# Generated by Django 6.0.2 on 2026-02-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0002_fooddonation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fraudulent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
