# Generated by Django 6.0.2 on 2026-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_saver', '0003_user_is_fraudulent_user_reward_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
